services:
  - type: web
    name: ecommerce-multivendor
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn ecommerce_multivendor.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.0
